### ISSUE TITLE
Bot restarting when losing connection

### ISSUE THREAD

**Issue by microwavekonijn** [dignityofwar/digbot#68]
So I don't know if it an issue, but I am going to monitor it. On staging the bot will disconnect and I think it will get throttled by Discord and it will then restart due to a time-out. I will keep an eye out for this and post logs whenever it happens.

*09:49 13-11-2018*
```
[8:48:19 AM] [EVENT] (Commands Antispam) releaseUser
[8:48:25 AM] [EVENT] (Performance) execute
[8:48:55 AM] [EVENT] (Performance) execute
[8:49:17 AM] [EVENT] (Commands Antispam) releaseCommand
[8:49:17 AM] [EVENT] (admin.js) fiveMinCheck
[8:49:17 AM] [INFO] (Mention Antispam) No roles were found in muteRole.members
[8:49:17 AM] [EVENT] (Command Channel Antispam) commandChannel release timer
[8:49:19 AM] [EVENT] (discordbot) reconnecting
[8:49:19 AM] [STATUS] (bot-events) Client disconected, attempting reconnection...
[8:49:19 AM] [WARNING] (bot-events) Bot got disconnected from Discord, reconnecting...
[8:49:19 AM] [DEBUG] (server) Wiped guild: "DigBot-staging"
[8:49:19 AM] [DEBUG] (discordbot) Restart clock started
[8:49:25 AM] [EVENT] (Performance) execute
[8:49:25 AM] [EVENT] (discordbot) message
[8:49:55 AM] [EVENT] (Performance) execute
[8:50:19 AM] [EVENT] (Commands Antispam) releaseUser
[8:50:19 AM] [EVENT] (discordbot) restart
[8:50:19 AM] [WARNING] (discordbot) Restarting bot due to connection timeout
[8:50:19 AM] [WARNING] (discordbot) Bot connection handling failed, destroying bot, re-attempting connection...
[8:50:19 AM] [EVENT] (discordbot) restart bot.destroy
[8:50:19 AM] [EVENT] (discordbot) restart bot destroyed
[8:50:19 AM] [DEBUG] (Bot succesfully destroyed, restarting) undefined
[8:50:19 AM] [EVENT] (discordbot) initBot
[8:50:19 AM] [DEBUG] (discordbot) Start clock started
[8:50:19 AM] [INFO] (discordbot) DIGBot, starting up.
[8:50:20 AM] [EVENT] (discordbot) disconnect
[8:50:20 AM] [DEBUG] (discordbot) Restart clock wiped
[8:50:20 AM] [STATUS] (bot-events) Client disconected
[8:50:20 AM] [INFO] (server) Server was marked as unready!
[8:50:20 AM] [DEBUG] (discordbot) Restart clock started
[8:50:20 AM] [EVENT] (discordbot) ready
[8:50:20 AM] [DEBUG] (discordbot) Restart clock wiped
[8:50:20 AM] [STATUS] (bot-events) Client succesfully reconnected
[8:50:20 AM] [INFO] (server) Updated server: DigBot-staging
[8:50:20 AM] [INFO] (server) Set connection time
[8:50:20 AM] [INFO] (server) Server was marked as ready!
[8:50:20 AM] [EVENT] (server) setMembersOnServer
[8:50:20 AM] [EVENT] (server) setMembersPlaying
[8:50:20 AM] [INFO] (server) Detected members playing change. New count: 0
[8:50:20 AM] [INFO] (bot-events) DIGBot, Online.
[8:50:20 AM] [DEBUG] (discordbot) Start clock wiped
[8:50:20 AM] [EVENT] (discordbot) login
[8:50:25 AM] [EVENT] (Performance) execute
[8:50:55 AM] [EVENT] (Performance) execute
[8:51:25 AM] [EVENT] (Performance) execute
```

**Comment by JamesLongman** [comment]
If you check the warning logs on live discord you'll see it happens a lot with our current bot too so it's not a new thing. I don't think we're being rate limited as we are nowhere near limits so I'm not really sure what we can do about this other than maybe handle it a bit more gracefully.

Unfortunately, it's obviously hard to repro on demand so it's hard to build better systems for it

**Comment by microwavekonijn** [comment]
Maybe, I am not sure, but having the bot restart 3 times in less then 24 hours after an update got my attention. That is why I will post the logs, then we can eventually zero-in on the problem if there is any.

**Comment by microwavekonijn** [comment]
*15-11-2018*
```
[9:53:09 AM] [EVENT] (Performance) execute
[9:53:39 AM] [EVENT] (Performance) execute
[9:54:09 AM] [EVENT] (Performance) execute
[9:54:39 AM] [EVENT] (Performance) execute
[9:54:47 AM] [EVENT] (discordbot) reconnecting
[9:54:47 AM] [STATUS] (bot-events) Client disconected, attempting reconnection...
[9:54:47 AM] [WARNING] (bot-events) Bot got disconnected from Discord, reconnecting...
[9:54:47 AM] [DEBUG] (server) Wiped guild: "DigBot-staging"
[9:54:47 AM] [DEBUG] (discordbot) Restart clock started
[9:54:53 AM] [EVENT] (discordbot) message
[9:55:08 AM] [EVENT] (admin.js) autodelete check
[9:55:08 AM] [WARNING] (server) Guild "503229946898939922" doesn't exist!
[9:55:08 AM] [EVENT] (Commands Antispam) releaseCommand
[9:55:08 AM] [EVENT] (admin.js) fiveMinCheck
[9:55:08 AM] [WARNING] (server) Guild "503229946898939922" doesn't exist!
/usr/src/digbot/src/lib/server/server.js:137
        if (this.getGuild(guild).roles.array().length === 0) {
                                ^

TypeError: Cannot read property 'roles' of null
    at Object.getRoles (/usr/src/digbot/src/lib/server/server.js:137:33)
    at Object.getRole (/usr/src/digbot/src/lib/server/server.js:127:19)
    at Object.release (/usr/src/digbot/src/lib/admin/antispam/mentionspam.js:163:31)
    at Timeout.fiveMinCheck [as _onTimeout] (/usr/src/digbot/src/lib/admin/admin.js:118:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! digbot@0.1.0 start: `node src/bot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the digbot@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-15T09_55_08_285Z-debug.log

> digbot@0.1.0 start /usr/src/digbot
> node src/bot.js

[9:55:10 AM] [EVENT] (discordbot) initBot
[9:55:10 AM] [INFO] (discordbot) DIGBot, starting up.
[9:55:11 AM] [EVENT] (discordbot) ready
[9:55:11 AM] [INFO] (bot-events) DIGBot, Online.
[9:55:11 AM] [INFO] (server) Set connection time
[9:55:11 AM] [INFO] (server) Channel digbot-log was set
[9:55:11 AM] [INFO] (server) Channel digbot was set
[9:55:11 AM] [INFO] (server) Channel developers was set
[9:55:11 AM] [INFO] (server) Channel staff was set
[9:55:11 AM] [INFO] (server) Channel general was set
[9:55:11 AM] [INFO] (server) Channel events was set
[9:55:11 AM] [INFO] (server) Channel streams was set
[9:55:11 AM] [INFO] (server) Channel ps2dig was set
[9:55:11 AM] [INFO] (server) Channel 💬 Chit Chat was set
[9:55:11 AM] [INFO] (server) Channel herebedragons was set
[9:55:11 AM] [DEBUG] (bot-events) Succesfully sent message
503229946898939922
[9:55:11 AM] [INFO] (server) Updated server: DigBot-staging
[9:55:11 AM] [EVENT] (server) setMembersOnServer
[9:55:11 AM] [EVENT] (server) setMembersPlaying
[9:55:11 AM] [INFO] (server) Detected members playing change. New count: 0
[9:55:11 AM] [INFO] (bot-events) Server member count: 7
[9:55:11 AM] [EVENT] (subBots) ready
[9:55:11 AM] [INFO] (server) Server was marked as ready!
[9:55:11 AM] [INFO] (server) Server boot marked as complete!
(node:16) DeprecationWarning: TextChannel#sendMessage: use TextChannel#send instead
[9:55:11 AM] [DEBUG] (discordbot) Start clock wiped
[9:55:11 AM] [EVENT] (discordbot) login
[9:55:11 AM] [EVENT] (discordbot) message
[9:55:13 AM] [EVENT] (admin.js) startchecks
[9:55:13 AM] [EVENT] (Channels Master) checkPositions
[9:55:13 AM] [EVENT] (Channel Positions) globalCheck
[9:55:20 AM] [DEBUG] (subBots) Sub bot succesfully sent message
```

**Comment by microwavekonijn** [comment]
*23-11-2018*
```
[5:43:37 PM] [INFO] (server) Stored server: DigBot-staging
[5:43:37 PM] [EVENT] (server) setMembersPlaying
[5:43:37 PM] [INFO] (server) Detected members playing change. New count: 1
[5:43:53 PM] [EVENT] (Commands Antispam) releaseUser
[5:43:53 PM] [EVENT] (Performance) execute
[5:44:23 PM] [EVENT] (Performance) execute
[5:44:50 PM] [EVENT] (discordbot) presenceUpdate
[5:44:50 PM] [INFO] (server) Stored server: DigBot-staging
[5:44:50 PM] [EVENT] (server) setMembersPlaying
[5:44:50 PM] [INFO] (server) Detected members playing change. New count: 1
[5:44:53 PM] [EVENT] (Commands Antispam) releaseCommand
[5:44:53 PM] [EVENT] (admin.js) fiveMinCheck
/usr/src/digbot/src/lib/admin/events.js:46
            logger.warning(TAG, `Was unable to get role ${eventObject.roles[i]} for event ${eventObj.name}`);
                                                          ^

ReferenceError: eventObject is not defined
    at alert (/usr/src/digbot/src/lib/admin/events.js:46:59)
    at preHourCheck (/usr/src/digbot/src/lib/admin/events.js:170:13)
    at Object.check (/usr/src/digbot/src/lib/admin/events.js:25:21)
    at Timeout.fiveMinCheck [as _onTimeout] (/usr/src/digbot/src/lib/admin/admin.js:116:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! digbot@0.1.0 start: `node src/bot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the digbot@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-23T17_44_53_653Z-debug.log

> digbot@0.1.0 start /usr/src/digbot
> node src/bot.js

[5:44:55 PM] [EVENT] (discordbot) initBot
[5:44:55 PM] [INFO] (discordbot) DIGBot, starting up.
[5:44:55 PM] [EVENT] (discordbot) ready
[5:44:55 PM] [INFO] (bot-events) DIGBot, Online.

```

**Comment by microwavekonijn** [comment]
On my developer bot I added more information to the log that logs disconnect events. After looking in to it is a normal disconnect with code 1000 and has something to do with cloudflare. There is a fix maybe, but I need to test it first. Stay tuned.

**Comment by microwavekonijn** [comment]
So this is the fix.
```
client.on('disconnect', () => client.login('token'));
```
I don't think the bot is prepared to handle this in it's current state, though I don't think it is a big problem. Only when it is trying to send something to the discord api when it is down it will fail (and leave it at that without retrying), but chances of that happening are very slim.
